### ISSUE TITLE
github.token path broken on MACOS

### ISSUE THREAD

**Issue by julian-poidevin** [strahlex/Qt-Deployment-Scripts#6]
github.token path seems to be broken when executing script `qt-release` on MacOS :

When executing this command
```Shell
sudo qt-release -v 0.4.0 -t 0.4.0 ./ressource/MBPMid2010-GPU-Fix-client_mac.ini 
```

Getting this error :
```Shell
loging in to GitHub...Traceback (most recent call last):
  File "/usr/bin/qt-release", line 230, in <module>
    release.run()
  File "/usr/bin/qt-release", line 223, in run
    self.loginToGitHub()
  File "/usr/bin/qt-release", line 150, in loginToGitHub
    with open(self.credentialsFile, 'r') as fd:
IOError: [Errno 2] No such file or directory: '/Users/Julian/.qt-release/github.token'
```

What can be done :
- [ ] Add [link to GitHub help](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to tell people how to generate token
- [ ]  Import path to GitHub token from configuration file

**Comment by julian-poidevin** [comment]
My bad, closing this one, didn't see `--authorize` option
